name: basic_action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sequential_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.title == 'basic_action' }}

    steps:
      - name: Sleep some time
        run: sleep 60
  
  second_job:
    runs-on: ubuntu-latest
    needs: [ sequential_job ]
    steps:
      - name: Sleep some time
        run: sleep 60
